// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type AuditLog struct {
	ID          int64
	At          string
	ActorUserID sql.NullInt64
	Action      string
	Target      sql.NullString
	Status      string
	MessageID   sql.NullInt64
	OldValue    sql.NullString
	NewValue    sql.NullString
	Error       sql.NullString
}

type BotConfig struct {
	Key             string
	Value           string
	UpdatedByUserID sql.NullInt64
	UpdatedAt       string
}

type ChannelLifecycleQueue struct {
	ID             int64
	ZulipEventID   int64
	ZulipEventType string
	LifecycleKind  string
	ChannelID      sql.NullInt64
	ChannelName    sql.NullString
	Op             sql.NullString
	PayloadJson    string
	Status         string
	Attempts       int64
	AvailableAt    string
	LockedAt       sql.NullString
	LockedBy       sql.NullString
	ProcessedAt    sql.NullString
	LastError      sql.NullString
	CreatedAt      string
}

type EventQueueState struct {
	ID          int64
	QueueID     string
	LastEventID int64
	UpdatedAt   string
}

type ProcessedMessage struct {
	MessageID   int64
	ProcessedAt string
}

type RawEvent struct {
	ID         int64
	QueueID    string
	EventID    int64
	EventType  string
	ReceivedAt string
	RawJson    string
}

type RestartRequest struct {
	ID                  int64
	Status              string
	RequestedByUserID   int64
	RequestMessageID    int64
	ResponseKind        string
	ChannelID           sql.NullInt64
	Topic               sql.NullString
	RecipientUserIds    string
	RequestedAt         string
	CompletedAt         sql.NullString
	CompletionMessageID sql.NullInt64
	Failure             sql.NullString
}

type SchemaMigration struct {
	Version   int64
	Name      string
	AppliedAt string
}

type UserRole struct {
	UserID          int64
	Role            string
	GrantedByUserID sql.NullInt64
	UpdatedAt       string
}
