// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const claimChannelLifecycleEntry = `-- name: ClaimChannelLifecycleEntry :execrows
UPDATE channel_lifecycle_queue
SET status = 'processing', locked_at = ?, locked_by = ?, attempts = attempts + 1
WHERE id = ? AND status = 'pending'
`

type ClaimChannelLifecycleEntryParams struct {
	LockedAt sql.NullString
	LockedBy sql.NullString
	ID       int64
}

func (q *Queries) ClaimChannelLifecycleEntry(ctx context.Context, arg ClaimChannelLifecycleEntryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimChannelLifecycleEntry, arg.LockedAt, arg.LockedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearEventQueueState = `-- name: ClearEventQueueState :exec
DELETE FROM event_queue_state
WHERE id = 1
`

func (q *Queries) ClearEventQueueState(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearEventQueueState)
	return err
}

const completeRestartRequest = `-- name: CompleteRestartRequest :exec
UPDATE restart_requests
SET status = ?, completed_at = ?, completion_message_id = ?, failure = ?
WHERE id = ?
`

type CompleteRestartRequestParams struct {
	Status              string
	CompletedAt         sql.NullString
	CompletionMessageID sql.NullInt64
	Failure             sql.NullString
	ID                  int64
}

func (q *Queries) CompleteRestartRequest(ctx context.Context, arg CompleteRestartRequestParams) error {
	_, err := q.db.ExecContext(ctx, completeRestartRequest,
		arg.Status,
		arg.CompletedAt,
		arg.CompletionMessageID,
		arg.Failure,
		arg.ID,
	)
	return err
}

const countAllChannelLifecycleEntries = `-- name: CountAllChannelLifecycleEntries :one
SELECT CAST(COUNT(*) AS INTEGER) AS count FROM channel_lifecycle_queue
`

func (q *Queries) CountAllChannelLifecycleEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllChannelLifecycleEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChannelLifecycleEntriesByStatus = `-- name: CountChannelLifecycleEntriesByStatus :many
SELECT status, CAST(COUNT(*) AS INTEGER) AS count
FROM channel_lifecycle_queue
GROUP BY status
ORDER BY status ASC
`

type CountChannelLifecycleEntriesByStatusRow struct {
	Status string
	Count  int64
}

func (q *Queries) CountChannelLifecycleEntriesByStatus(ctx context.Context) ([]CountChannelLifecycleEntriesByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countChannelLifecycleEntriesByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountChannelLifecycleEntriesByStatusRow{}
	for rows.Next() {
		var i CountChannelLifecycleEntriesByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countProcessedMessages = `-- name: CountProcessedMessages :one
SELECT COUNT(*) AS count
FROM processed_messages
`

func (q *Queries) CountProcessedMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProcessedMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRawEvents = `-- name: CountRawEvents :one
SELECT COUNT(*) AS count
FROM raw_events
`

func (q *Queries) CountRawEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRawEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRestartRequest = `-- name: CreateRestartRequest :exec
INSERT OR IGNORE INTO restart_requests(
  status,
  requested_by_user_id,
  request_message_id,
  response_kind,
  channel_id,
  topic,
  recipient_user_ids,
  requested_at
) VALUES ('requested', ?, ?, ?, ?, ?, ?, ?)
`

type CreateRestartRequestParams struct {
	RequestedByUserID int64
	RequestMessageID  int64
	ResponseKind      string
	ChannelID         sql.NullInt64
	Topic             sql.NullString
	RecipientUserIds  string
	RequestedAt       string
}

func (q *Queries) CreateRestartRequest(ctx context.Context, arg CreateRestartRequestParams) error {
	_, err := q.db.ExecContext(ctx, createRestartRequest,
		arg.RequestedByUserID,
		arg.RequestMessageID,
		arg.ResponseKind,
		arg.ChannelID,
		arg.Topic,
		arg.RecipientUserIds,
		arg.RequestedAt,
	)
	return err
}

const deleteCompletedChannelLifecycleEntries = `-- name: DeleteCompletedChannelLifecycleEntries :execrows
DELETE FROM channel_lifecycle_queue
WHERE status IN ('done', 'skipped') AND processed_at < ?
`

func (q *Queries) DeleteCompletedChannelLifecycleEntries(ctx context.Context, processedAt sql.NullString) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCompletedChannelLifecycleEntries, processedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredProcessedMessages = `-- name: DeleteExpiredProcessedMessages :execrows
DELETE FROM processed_messages
WHERE processed_at < ?
`

func (q *Queries) DeleteExpiredProcessedMessages(ctx context.Context, processedAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredProcessedMessages, processedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredRawEvents = `-- name: DeleteExpiredRawEvents :execrows
DELETE FROM raw_events
WHERE received_at < ?
`

func (q *Queries) DeleteExpiredRawEvents(ctx context.Context, receivedAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredRawEvents, receivedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteLocalUserRole = `-- name: DeleteLocalUserRole :exec
DELETE FROM user_roles
WHERE user_id = ?
`

func (q *Queries) DeleteLocalUserRole(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteLocalUserRole, userID)
	return err
}

const enqueueChannelLifecycleItem = `-- name: EnqueueChannelLifecycleItem :exec
INSERT OR IGNORE INTO channel_lifecycle_queue(
  zulip_event_id, zulip_event_type, lifecycle_kind,
  channel_id, channel_name, op, payload_json,
  status, attempts, available_at, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, 'pending', 0, ?, ?)
`

type EnqueueChannelLifecycleItemParams struct {
	ZulipEventID   int64
	ZulipEventType string
	LifecycleKind  string
	ChannelID      sql.NullInt64
	ChannelName    sql.NullString
	Op             sql.NullString
	PayloadJson    string
	AvailableAt    string
	CreatedAt      string
}

func (q *Queries) EnqueueChannelLifecycleItem(ctx context.Context, arg EnqueueChannelLifecycleItemParams) error {
	_, err := q.db.ExecContext(ctx, enqueueChannelLifecycleItem,
		arg.ZulipEventID,
		arg.ZulipEventType,
		arg.LifecycleKind,
		arg.ChannelID,
		arg.ChannelName,
		arg.Op,
		arg.PayloadJson,
		arg.AvailableAt,
		arg.CreatedAt,
	)
	return err
}

const getChannelLifecycleEntry = `-- name: GetChannelLifecycleEntry :one
SELECT id, zulip_event_id, zulip_event_type, lifecycle_kind,
  channel_id, channel_name, op, payload_json,
  status, attempts, available_at, locked_at, locked_by, processed_at, last_error, created_at
FROM channel_lifecycle_queue
WHERE id = ?
`

func (q *Queries) GetChannelLifecycleEntry(ctx context.Context, id int64) (ChannelLifecycleQueue, error) {
	row := q.db.QueryRowContext(ctx, getChannelLifecycleEntry, id)
	var i ChannelLifecycleQueue
	err := row.Scan(
		&i.ID,
		&i.ZulipEventID,
		&i.ZulipEventType,
		&i.LifecycleKind,
		&i.ChannelID,
		&i.ChannelName,
		&i.Op,
		&i.PayloadJson,
		&i.Status,
		&i.Attempts,
		&i.AvailableAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.ProcessedAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const getConfigValue = `-- name: GetConfigValue :one
SELECT value
FROM bot_config
WHERE key = ?
`

func (q *Queries) GetConfigValue(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getConfigValue, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getEventQueueState = `-- name: GetEventQueueState :one
SELECT queue_id, last_event_id, updated_at
FROM event_queue_state
WHERE id = 1
`

type GetEventQueueStateRow struct {
	QueueID     string
	LastEventID int64
	UpdatedAt   string
}

func (q *Queries) GetEventQueueState(ctx context.Context) (GetEventQueueStateRow, error) {
	row := q.db.QueryRowContext(ctx, getEventQueueState)
	var i GetEventQueueStateRow
	err := row.Scan(&i.QueueID, &i.LastEventID, &i.UpdatedAt)
	return i, err
}

const getLatestActiveRestartRequestID = `-- name: GetLatestActiveRestartRequestID :one
SELECT id
FROM restart_requests
WHERE status IN ('requested', 'in_progress')
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetLatestActiveRestartRequestID(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLatestActiveRestartRequestID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getLocalUserRole = `-- name: GetLocalUserRole :one
SELECT role
FROM user_roles
WHERE user_id = ?
`

func (q *Queries) GetLocalUserRole(ctx context.Context, userID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getLocalUserRole, userID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getPendingRestartRequest = `-- name: GetPendingRestartRequest :one
SELECT
  id,
  requested_by_user_id,
  request_message_id,
  response_kind,
  channel_id,
  topic,
  recipient_user_ids,
  requested_at
FROM restart_requests
WHERE status IN ('requested', 'in_progress')
ORDER BY id DESC
LIMIT 1
`

type GetPendingRestartRequestRow struct {
	ID                int64
	RequestedByUserID int64
	RequestMessageID  int64
	ResponseKind      string
	ChannelID         sql.NullInt64
	Topic             sql.NullString
	RecipientUserIds  string
	RequestedAt       string
}

func (q *Queries) GetPendingRestartRequest(ctx context.Context) (GetPendingRestartRequestRow, error) {
	row := q.db.QueryRowContext(ctx, getPendingRestartRequest)
	var i GetPendingRestartRequestRow
	err := row.Scan(
		&i.ID,
		&i.RequestedByUserID,
		&i.RequestMessageID,
		&i.ResponseKind,
		&i.ChannelID,
		&i.Topic,
		&i.RecipientUserIds,
		&i.RequestedAt,
	)
	return i, err
}

const getProcessedMessage = `-- name: GetProcessedMessage :one
SELECT message_id
FROM processed_messages
WHERE message_id = ?
`

func (q *Queries) GetProcessedMessage(ctx context.Context, messageID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getProcessedMessage, messageID)
	var message_id int64
	err := row.Scan(&message_id)
	return message_id, err
}

const getRestartRequestIDByMessageID = `-- name: GetRestartRequestIDByMessageID :one
SELECT id
FROM restart_requests
WHERE request_message_id = ?
`

func (q *Queries) GetRestartRequestIDByMessageID(ctx context.Context, requestMessageID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getRestartRequestIDByMessageID, requestMessageID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAuditRecords = `-- name: ListAuditRecords :many
SELECT
  at,
  actor_user_id,
  action,
  target,
  status,
  message_id,
  old_value,
  new_value,
  error
FROM audit_log
ORDER BY id
`

type ListAuditRecordsRow struct {
	At          string
	ActorUserID sql.NullInt64
	Action      string
	Target      sql.NullString
	Status      string
	MessageID   sql.NullInt64
	OldValue    sql.NullString
	NewValue    sql.NullString
	Error       sql.NullString
}

func (q *Queries) ListAuditRecords(ctx context.Context) ([]ListAuditRecordsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditRecordsRow{}
	for rows.Next() {
		var i ListAuditRecordsRow
		if err := rows.Scan(
			&i.At,
			&i.ActorUserID,
			&i.Action,
			&i.Target,
			&i.Status,
			&i.MessageID,
			&i.OldValue,
			&i.NewValue,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocalUserRoles = `-- name: ListLocalUserRoles :many
SELECT user_id, role, granted_by_user_id, updated_at
FROM user_roles
ORDER BY updated_at DESC, user_id ASC
`

func (q *Queries) ListLocalUserRoles(ctx context.Context) ([]UserRole, error) {
	rows, err := q.db.QueryContext(ctx, listLocalUserRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserRole{}
	for rows.Next() {
		var i UserRole
		if err := rows.Scan(
			&i.UserID,
			&i.Role,
			&i.GrantedByUserID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingChannelLifecycleEntries = `-- name: ListPendingChannelLifecycleEntries :many
SELECT id, zulip_event_id, zulip_event_type, lifecycle_kind,
  channel_id, channel_name, op, payload_json,
  status, attempts, available_at, locked_at, locked_by, processed_at, last_error, created_at
FROM channel_lifecycle_queue
WHERE status = 'pending' AND available_at <= ?
ORDER BY available_at ASC, id ASC
LIMIT ?
`

type ListPendingChannelLifecycleEntriesParams struct {
	AvailableAt string
	Limit       int64
}

func (q *Queries) ListPendingChannelLifecycleEntries(ctx context.Context, arg ListPendingChannelLifecycleEntriesParams) ([]ChannelLifecycleQueue, error) {
	rows, err := q.db.QueryContext(ctx, listPendingChannelLifecycleEntries, arg.AvailableAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelLifecycleQueue{}
	for rows.Next() {
		var i ChannelLifecycleQueue
		if err := rows.Scan(
			&i.ID,
			&i.ZulipEventID,
			&i.ZulipEventType,
			&i.LifecycleKind,
			&i.ChannelID,
			&i.ChannelName,
			&i.Op,
			&i.PayloadJson,
			&i.Status,
			&i.Attempts,
			&i.AvailableAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.ProcessedAt,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChannelLifecycleEntryDone = `-- name: MarkChannelLifecycleEntryDone :exec
UPDATE channel_lifecycle_queue
SET status = 'done', processed_at = ?, locked_at = NULL, locked_by = NULL
WHERE id = ?
`

type MarkChannelLifecycleEntryDoneParams struct {
	ProcessedAt sql.NullString
	ID          int64
}

func (q *Queries) MarkChannelLifecycleEntryDone(ctx context.Context, arg MarkChannelLifecycleEntryDoneParams) error {
	_, err := q.db.ExecContext(ctx, markChannelLifecycleEntryDone, arg.ProcessedAt, arg.ID)
	return err
}

const markChannelLifecycleEntryFailed = `-- name: MarkChannelLifecycleEntryFailed :exec
UPDATE channel_lifecycle_queue
SET status = 'failed', last_error = ?, processed_at = ?, locked_at = NULL, locked_by = NULL
WHERE id = ?
`

type MarkChannelLifecycleEntryFailedParams struct {
	LastError   sql.NullString
	ProcessedAt sql.NullString
	ID          int64
}

func (q *Queries) MarkChannelLifecycleEntryFailed(ctx context.Context, arg MarkChannelLifecycleEntryFailedParams) error {
	_, err := q.db.ExecContext(ctx, markChannelLifecycleEntryFailed, arg.LastError, arg.ProcessedAt, arg.ID)
	return err
}

const markChannelLifecycleEntrySkipped = `-- name: MarkChannelLifecycleEntrySkipped :exec
UPDATE channel_lifecycle_queue
SET status = 'skipped', processed_at = ?, locked_at = NULL, locked_by = NULL
WHERE id = ?
`

type MarkChannelLifecycleEntrySkippedParams struct {
	ProcessedAt sql.NullString
	ID          int64
}

func (q *Queries) MarkChannelLifecycleEntrySkipped(ctx context.Context, arg MarkChannelLifecycleEntrySkippedParams) error {
	_, err := q.db.ExecContext(ctx, markChannelLifecycleEntrySkipped, arg.ProcessedAt, arg.ID)
	return err
}

const markMessageProcessed = `-- name: MarkMessageProcessed :exec
INSERT OR IGNORE INTO processed_messages(message_id, processed_at)
VALUES (?, ?)
`

type MarkMessageProcessedParams struct {
	MessageID   int64
	ProcessedAt string
}

func (q *Queries) MarkMessageProcessed(ctx context.Context, arg MarkMessageProcessedParams) error {
	_, err := q.db.ExecContext(ctx, markMessageProcessed, arg.MessageID, arg.ProcessedAt)
	return err
}

const markRestartInProgress = `-- name: MarkRestartInProgress :execrows
UPDATE restart_requests
SET status = ?, completed_at = NULL, completion_message_id = NULL, failure = NULL
WHERE id = ? AND status IN ('requested', 'in_progress')
`

type MarkRestartInProgressParams struct {
	Status string
	ID     int64
}

func (q *Queries) MarkRestartInProgress(ctx context.Context, arg MarkRestartInProgressParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markRestartInProgress, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordAudit = `-- name: RecordAudit :exec
INSERT INTO audit_log(
  at,
  actor_user_id,
  action,
  target,
  status,
  message_id,
  old_value,
  new_value,
  error
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type RecordAuditParams struct {
	At          string
	ActorUserID sql.NullInt64
	Action      string
	Target      sql.NullString
	Status      string
	MessageID   sql.NullInt64
	OldValue    sql.NullString
	NewValue    sql.NullString
	Error       sql.NullString
}

func (q *Queries) RecordAudit(ctx context.Context, arg RecordAuditParams) error {
	_, err := q.db.ExecContext(ctx, recordAudit,
		arg.At,
		arg.ActorUserID,
		arg.Action,
		arg.Target,
		arg.Status,
		arg.MessageID,
		arg.OldValue,
		arg.NewValue,
		arg.Error,
	)
	return err
}

const resetAllFailedChannelLifecycleEntries = `-- name: ResetAllFailedChannelLifecycleEntries :execrows
UPDATE channel_lifecycle_queue
SET status = 'pending', locked_at = NULL, locked_by = NULL, processed_at = NULL, last_error = NULL, available_at = ?
WHERE status = 'failed'
`

func (q *Queries) ResetAllFailedChannelLifecycleEntries(ctx context.Context, availableAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, resetAllFailedChannelLifecycleEntries, availableAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resetChannelLifecycleEntryToPending = `-- name: ResetChannelLifecycleEntryToPending :execrows
UPDATE channel_lifecycle_queue
SET status = 'pending', locked_at = NULL, locked_by = NULL, processed_at = NULL, last_error = NULL, available_at = ?
WHERE id = ?
`

type ResetChannelLifecycleEntryToPendingParams struct {
	AvailableAt string
	ID          int64
}

func (q *Queries) ResetChannelLifecycleEntryToPending(ctx context.Context, arg ResetChannelLifecycleEntryToPendingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resetChannelLifecycleEntryToPending, arg.AvailableAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const saveEventQueueState = `-- name: SaveEventQueueState :exec
INSERT INTO event_queue_state(id, queue_id, last_event_id, updated_at)
VALUES (1, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  queue_id = excluded.queue_id,
  last_event_id = excluded.last_event_id,
  updated_at = excluded.updated_at
`

type SaveEventQueueStateParams struct {
	QueueID     string
	LastEventID int64
	UpdatedAt   string
}

func (q *Queries) SaveEventQueueState(ctx context.Context, arg SaveEventQueueStateParams) error {
	_, err := q.db.ExecContext(ctx, saveEventQueueState, arg.QueueID, arg.LastEventID, arg.UpdatedAt)
	return err
}

const schemaMigrationName = `-- name: SchemaMigrationName :one
SELECT name
FROM schema_migrations
WHERE version = ?
`

func (q *Queries) SchemaMigrationName(ctx context.Context, version int64) (string, error) {
	row := q.db.QueryRowContext(ctx, schemaMigrationName, version)
	var name string
	err := row.Scan(&name)
	return name, err
}

const schemaVersion = `-- name: SchemaVersion :one
SELECT CAST(COALESCE(MAX(version), 0) AS INTEGER) AS version
FROM schema_migrations
`

func (q *Queries) SchemaVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, schemaVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const setConfigValue = `-- name: SetConfigValue :exec
INSERT INTO bot_config(key, value, updated_by_user_id, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(key) DO UPDATE SET
  value = excluded.value,
  updated_by_user_id = excluded.updated_by_user_id,
  updated_at = excluded.updated_at
`

type SetConfigValueParams struct {
	Key             string
	Value           string
	UpdatedByUserID sql.NullInt64
	UpdatedAt       string
}

func (q *Queries) SetConfigValue(ctx context.Context, arg SetConfigValueParams) error {
	_, err := q.db.ExecContext(ctx, setConfigValue,
		arg.Key,
		arg.Value,
		arg.UpdatedByUserID,
		arg.UpdatedAt,
	)
	return err
}

const setLocalUserRole = `-- name: SetLocalUserRole :exec
INSERT INTO user_roles(user_id, role, granted_by_user_id, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(user_id) DO UPDATE SET
  role = excluded.role,
  granted_by_user_id = excluded.granted_by_user_id,
  updated_at = excluded.updated_at
`

type SetLocalUserRoleParams struct {
	UserID          int64
	Role            string
	GrantedByUserID sql.NullInt64
	UpdatedAt       string
}

func (q *Queries) SetLocalUserRole(ctx context.Context, arg SetLocalUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, setLocalUserRole,
		arg.UserID,
		arg.Role,
		arg.GrantedByUserID,
		arg.UpdatedAt,
	)
	return err
}

const storeRawEvent = `-- name: StoreRawEvent :exec
INSERT OR IGNORE INTO raw_events(queue_id, event_id, event_type, received_at, raw_json)
VALUES (?, ?, ?, ?, ?)
`

type StoreRawEventParams struct {
	QueueID    string
	EventID    int64
	EventType  string
	ReceivedAt string
	RawJson    string
}

func (q *Queries) StoreRawEvent(ctx context.Context, arg StoreRawEventParams) error {
	_, err := q.db.ExecContext(ctx, storeRawEvent,
		arg.QueueID,
		arg.EventID,
		arg.EventType,
		arg.ReceivedAt,
		arg.RawJson,
	)
	return err
}

const trimProcessedMessages = `-- name: TrimProcessedMessages :execrows
DELETE FROM processed_messages
WHERE message_id NOT IN (
  SELECT message_id
  FROM processed_messages
  ORDER BY processed_at DESC, message_id DESC
  LIMIT ?
)
`

func (q *Queries) TrimProcessedMessages(ctx context.Context, limit int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, trimProcessedMessages, limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const trimRawEvents = `-- name: TrimRawEvents :execrows
DELETE FROM raw_events
WHERE id NOT IN (
  SELECT id
  FROM raw_events
  ORDER BY received_at DESC, id DESC
  LIMIT ?
)
`

func (q *Queries) TrimRawEvents(ctx context.Context, limit int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, trimRawEvents, limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
