//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path"
	"reflect"
	"sort"
	"strings"

	zulipclient "github.com/tum-zulip/go-zulip/zulip/client"
)

const outputPath = "client_impl.go"

type importSet map[string]string

var roundRobinMethods = []string{
	"AddAlertWords",
	"ArchiveChannel",
	"CreateChannel",
	"CreateChannelFolder",
	"CreateUser",
	"CreateUserGroup",
	"DeactivateCustomEmoji",
	"DeactivateUser",
	"DeactivateUserGroup",
	"GetAlertWords",
	"GetChannelByID",
	"GetChannelEmailAddress",
	"GetChannelFolders",
	"GetChannelID",
	"GetChannelTopics",
	"GetChannels",
	"GetSubscribers",
	"GetUser",
	"GetUserByEmail",
	"GetUserGroupMembers",
	"GetUserGroupSubgroups",
	"GetUserGroups",
	"GetUsers",
	"RenderMessage",
	"UpdateChannel",
	"UpdateChannelFolder",
	"UpdateLinkifier",
	"UpdateUserGroup",
}

var roundRobinMethodSet = func() map[string]struct{} {
	methods := make(map[string]struct{}, len(roundRobinMethods))
	for _, method := range roundRobinMethods {
		methods[method] = struct{}{}
	}
	return methods
}()

func main() {
	source, err := generate()
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile(outputPath, source, 0o644); err != nil {
		panic(err)
	}
}

func generate() ([]byte, error) {
	clientType := reflect.TypeOf((*zulipclient.Client)(nil)).Elem()
	imports := importSet{}
	var methods bytes.Buffer

	for i := 0; i < clientType.NumMethod(); i++ {
		method := clientType.Method(i)
		if method.Name == "GetStatistics" {
			continue
		}
		if err := writeMethod(&methods, imports, method); err != nil {
			return nil, fmt.Errorf("write method %s: %w", method.Name, err)
		}
	}

	var source bytes.Buffer
	source.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	source.WriteString("package zuliproundrobin\n\n")
	writeImports(&source, imports)
	source.WriteByte('\n')
	source.Write(methods.Bytes())

	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w\n%s", err, source.String())
	}
	return formatted, nil
}

func writeMethod(buf *bytes.Buffer, imports importSet, method reflect.Method) error {
	methodType := method.Type
	params, args := methodParams(imports, methodType)
	results := methodResults(imports, methodType)

	fmt.Fprintf(buf, "func (c *Client) %s(%s) %s {\n", method.Name, params, results)
	if strings.HasSuffix(method.Name, "Execute") {
		if err := validateRequestExecuteMethod(method); err != nil {
			return err
		}
		if methodType.NumOut() == 0 {
			buf.WriteString("\tp0.Execute()\n")
		} else {
			buf.WriteString("\treturn p0.Execute()\n")
		}
		buf.WriteString("}\n\n")
		return nil
	}

	client := "c.client"
	if _, ok := roundRobinMethodSet[method.Name]; ok {
		client = "c.next()"
	}
	if methodType.NumOut() == 0 {
		fmt.Fprintf(buf, "\t%s.%s(%s)\n", client, method.Name, args)
	} else {
		fmt.Fprintf(buf, "\treturn %s.%s(%s)\n", client, method.Name, args)
	}
	buf.WriteString("}\n\n")
	return nil
}

func validateRequestExecuteMethod(method reflect.Method) error {
	methodType := method.Type
	if methodType.NumIn() != 1 {
		return fmt.Errorf("execute method has %d parameters, want 1 request parameter", methodType.NumIn())
	}

	requestType := methodType.In(0)
	requestExecute, ok := requestType.MethodByName("Execute")
	if !ok {
		return fmt.Errorf("%s has no Execute method", requestType)
	}
	if requestExecute.Type.NumIn() != 1 {
		return fmt.Errorf("%s.Execute has %d parameters, want 0", requestType, requestExecute.Type.NumIn()-1)
	}
	if requestExecute.Type.NumOut() != methodType.NumOut() {
		return fmt.Errorf(
			"%s.Execute has %d results, want %d",
			requestType,
			requestExecute.Type.NumOut(),
			methodType.NumOut(),
		)
	}
	for i := 0; i < methodType.NumOut(); i++ {
		if requestExecute.Type.Out(i) != methodType.Out(i) {
			return fmt.Errorf(
				"%s.Execute result %d is %s, want %s",
				requestType,
				i,
				requestExecute.Type.Out(i),
				methodType.Out(i),
			)
		}
	}
	return nil
}

func methodParams(imports importSet, methodType reflect.Type) (string, string) {
	params := make([]string, 0, methodType.NumIn())
	args := make([]string, 0, methodType.NumIn())
	for i := 0; i < methodType.NumIn(); i++ {
		name := fmt.Sprintf("p%d", i)
		paramType := methodType.In(i)
		rendered := renderType(imports, paramType)
		arg := name
		if methodType.IsVariadic() && i == methodType.NumIn()-1 {
			rendered = "..." + renderType(imports, paramType.Elem())
			arg += "..."
		}
		params = append(params, name+" "+rendered)
		args = append(args, arg)
	}
	return strings.Join(params, ", "), strings.Join(args, ", ")
}

func methodResults(imports importSet, methodType reflect.Type) string {
	switch methodType.NumOut() {
	case 0:
		return ""
	case 1:
		return renderType(imports, methodType.Out(0))
	default:
		results := make([]string, 0, methodType.NumOut())
		for i := 0; i < methodType.NumOut(); i++ {
			results = append(results, renderType(imports, methodType.Out(i)))
		}
		return "(" + strings.Join(results, ", ") + ")"
	}
}

func renderType(imports importSet, typ reflect.Type) string {
	if typ.Name() != "" {
		if pkgPath := typ.PkgPath(); pkgPath != "" {
			name := packageQualifier(typ)
			imports[pkgPath] = name
			return name + "." + typ.Name()
		}
		return typ.Name()
	}

	switch typ.Kind() {
	case reflect.Pointer:
		return "*" + renderType(imports, typ.Elem())
	case reflect.Slice:
		return "[]" + renderType(imports, typ.Elem())
	case reflect.Array:
		return fmt.Sprintf("[%d]%s", typ.Len(), renderType(imports, typ.Elem()))
	case reflect.Map:
		return "map[" + renderType(imports, typ.Key()) + "]" + renderType(imports, typ.Elem())
	case reflect.Chan:
		switch typ.ChanDir() {
		case reflect.RecvDir:
			return "<-chan " + renderType(imports, typ.Elem())
		case reflect.SendDir:
			return "chan<- " + renderType(imports, typ.Elem())
		default:
			return "chan " + renderType(imports, typ.Elem())
		}
	case reflect.Func:
		return renderFuncType(imports, typ)
	case reflect.Interface:
		if typ.NumMethod() == 0 {
			return "interface{}"
		}
	}
	return typ.String()
}

func renderFuncType(imports importSet, typ reflect.Type) string {
	params := make([]string, 0, typ.NumIn())
	for i := 0; i < typ.NumIn(); i++ {
		rendered := renderType(imports, typ.In(i))
		if typ.IsVariadic() && i == typ.NumIn()-1 {
			rendered = "..." + renderType(imports, typ.In(i).Elem())
		}
		params = append(params, rendered)
	}

	results := methodResults(imports, typ)
	if results != "" {
		results = " " + results
	}
	return "func(" + strings.Join(params, ", ") + ")" + results
}

func packageQualifier(typ reflect.Type) string {
	rendered := typ.String()
	qualifier, _, ok := strings.Cut(rendered, ".")
	if ok {
		qualifier = strings.TrimPrefix(qualifier, "*")
		if qualifier != "" && !strings.ContainsAny(qualifier, "[]<-/") {
			return qualifier
		}
	}
	return path.Base(typ.PkgPath())
}

func writeImports(buf *bytes.Buffer, imports importSet) {
	var stdlibPaths []string
	var thirdPartyPaths []string
	for importPath := range imports {
		if isStandardLibraryImport(importPath) {
			stdlibPaths = append(stdlibPaths, importPath)
			continue
		}
		thirdPartyPaths = append(thirdPartyPaths, importPath)
	}
	sort.Strings(stdlibPaths)
	sort.Strings(thirdPartyPaths)

	buf.WriteString("import (\n")
	for _, importPath := range stdlibPaths {
		writeImport(buf, imports, importPath)
	}
	if len(stdlibPaths) > 0 && len(thirdPartyPaths) > 0 {
		buf.WriteByte('\n')
	}
	for _, importPath := range thirdPartyPaths {
		writeImport(buf, imports, importPath)
	}
	buf.WriteString(")\n")
}

func writeImport(buf *bytes.Buffer, imports importSet, importPath string) {
	name := imports[importPath]
	defaultName := path.Base(importPath)
	if name != defaultName {
		fmt.Fprintf(buf, "\t%s %q\n", name, importPath)
		return
	}
	fmt.Fprintf(buf, "\t%q\n", importPath)
}

func isStandardLibraryImport(importPath string) bool {
	first, _, _ := strings.Cut(importPath, "/")
	return !strings.Contains(first, ".")
}
